version: '3'

services:
  postgresql:
    image: 'bitnami/postgresql'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data_temp:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=database

volumes:
  postgresql_data_temp: